In [1]:
import numpy as np

# 과제 1.

In [17]:
arr1 = np.arange(1,51)# arange함수를 사용하여 1 ~ 51미만의 정수로 구성된 배열 선언
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [18]:
arr2 = arr1[np.where(arr1%2==0)].reshape((5,5))# 짝수 조건을 통과한 원소는 reshape을 통해 5 x 5 로 변환
arr3 = arr1[np.where(arr1%2==1)].reshape((5,5))# 홀수 조건을 통과한 원소를 reshape을 통해 5 x 5 로 변환
print("짝수 배열 :\n", arr2,'\n홀수 배열 :\n',arr2)

짝수 배열 :
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]] 
홀수 배열 :
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]


In [19]:
arr2 = np.transpose(arr2)# 짝수 배열을 전치변환
arr3 = np.transpose(arr3)# 홀수 배열을 전치변환
print("짝수 배열을 전치 변환 :\n", arr2,'\n홀수 배열을 전치 변환 :\n',arr3)

짝수 배열을 전치 변환 :
 [[ 2 12 22 32 42]
 [ 4 14 24 34 44]
 [ 6 16 26 36 46]
 [ 8 18 28 38 48]
 [10 20 30 40 50]] 
홀수 배열을 전치 변환 :
 [[ 1 11 21 31 41]
 [ 3 13 23 33 43]
 [ 5 15 25 35 45]
 [ 7 17 27 37 47]
 [ 9 19 29 39 49]]


In [20]:
arr4 = np.dot(arr3, arr2)# 홀수 배열과 짝수 배열을 내적
print(arr4)

[[ 830 1880 2930 3980 5030]
 [ 890 2040 3190 4340 5490]
 [ 950 2200 3450 4700 5950]
 [1010 2360 3710 5060 6410]
 [1070 2520 3970 5420 6870]]


# 과제 2.

In [53]:
li1 = np.array([1, 2, 3, 5, 3, 4, 3, 6, 9, 7, 0, 8, 7, 10])
li2 = np.array([7, 2, 10, 5, 7, 4, 9, 1, 9, 8, 0, 3, 7, 6])
li3 = li1[np.where(li1==li2)]#li1과 li2의 서로 같은 인덱스에서 같은 숫자인경우 만 배열로 변환
li4 = np.where(li1 == li2) # li1과 li2에서 모두 존재하는 요소의 색인을 저장함
print("두 배열에 모두 존재하는 요소 : ", li3, '\n두 배열에 모두 존재하는 요소의 색인 위치 :', li4)

두 배열에 모두 존재하는 요소 :  [2 5 4 9 0 7] 
두 배열에 모두 존재하는 요소의 색인 위치 : (array([ 1,  3,  5,  8, 10, 12], dtype=int64),)


In [54]:
li3 = li3.reshape((2,3))# 2행 3열의 형태로 배열의 형태를 변환한다.
print(li3)

[[2 5 4]
 [9 0 7]]


In [45]:
li3_max = np.max(li3, axis = 0)# 배열의 최대값을 저장하는 배열 선언 aixs = 0은 열을 기준으로 함
li3_argmax = np.argmax(li3, axis = 0)# 배열의 최대값의 index를 저장하는 배열 선언
print('배열의 최대값 : ', li3_max, "최대값의 색인 위치 : ", li3_argmax)

배열의 최대값 :  [9 5 7] 최대값의 색인 위치 :  [1 0 1]


In [47]:
li3_min = np.min(li3, axis = 1)# 배열의 최솟값을 저장하는 배열 선언 axis = 1은 행을 기준으로 함
li3_argmin = np.argmin(li3, axis = 1)# 배열의 최솟값의 index를 저장하는 배열 선언
print("배열의 최솟값 :", li3_min, '최솟값의 색인 위치 :', li3_argmin)

배열의 최솟값 : [2 0] 최솟값의 색인 위치 : [0 1]
